http://localhost:8000/api/my-teams/papers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6IkZhcmloYSBNYXp1bWRlciBTaW50aHkiLCJlbWFpbCI6InRvYXNlYW5lbG1haEBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImVtYWlsVmVyaWZpZWQiOnRydWUsImlhdCI6MTc1NTAxNzIzMiwiZXhwIjoxNzU3NjA5MjMyfQ.TQf6AXDwfmkDe4qrM6r4-iyqiZOrlnM9vRQe9wv8xio
Content-Type: application/json

